name: Construire et pousser des images Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and push backend image
      - name: Construire et pousser le backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crm-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/crm-backend

      # 4. Build and push frontend image
      - name: Construire et pousser le frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crm-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/crm-frontend